# Generated by Django 5.0 on 2024-07-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='ms',
            new_name='file',
        ),
    ]
